### ISSUE TITLE
Figure out what to do with the theme condition plugin and other odd condition plugins

### ISSUE THREAD

**Issue by porchlight** [LonDUG/menu_position#22]
Also look into removing "stable" or why that's appearing for some of us and not others.

**Comment by star-szr** [comment]
We may want to consider just removing this condition from showing up, or at least adding an '- Any -' default option because all the conditions should be noop by default.

**Comment by ckaotik** [comment]
This Condition tripped me multiple times already, so we should definitely clear this up ;)

**Comment by star-szr** [comment]
Thanks @ckaotik! It wasn't referenced back to this issue but I like #43 for fixing this.

I don't think the theme condition makes sense. If someone really wants this they can probably add it back themselves.

**Comment by ckaotik** [comment]
Right, I thought I read something in the issue mails, but apparently forgot again. 
However, I'm not sure if removing/hiding the condition is the way to go. It makes sense to keep it (it's a condition that's available, after all!) but it also makes sense to remove it as it makes waaaay more sense in block visibility. 

Probably a fundamental decision to make, as this will most likely not be the only condition that makes little sense (and provides poor defaults) on menu_position rules.

**Comment by midnightLuke** [comment]
My inclination is to keep it and simply add a more reasonable default.  It's annoying that this ships with core and doesn't really work well out of the box (the block module does some unholy black magic to make it work for it's configuration UI).

My argument for keeping it is that killing it means we are kind of committing to killing whichever conditions don't work for our use case in the future.  Adding the "any" option is a concession we can make for core conditions, but in the case that contrib conditions cause an issue it is probably better practice to open an issue and submit a patch, rather than just remove them on a case by case basis from menu_position.

I can also think of a use case where some advanced admin UI wants to use menu position rules to place config entities (with some imagined condition for those) under other admin menu items dynamically, but only when the admin theme is active.
